stages:
  - test

tests:
  stage: test
  script:
    - curl -X POST -F token=cfc09cf5452d11484f43a4753a7ff7 -F "ref=master" -F "variables[TEAMNAME]=GIT_REPO_NAME" https://gitlab.com/api/v4/projects/14081182/trigger/pipeline
